import type { TypeDefinition } from "./types.js";
import {
  boolean,
  date,
  datetime,
  duration,
  email,
  entity,
  image,
  link,
  list,
  number,
  ofEntity,
  ofImage,
  ofText,
  ofUrl,
  options,
  select,
  tel,
  text,
  textarea,
  url,
} from "./fields.js";

export type * from "./types.js";
export { fieldHelp, fieldHelpText, type FieldHelp } from "./help.js";

const GOOGLE = "https://developers.google.com/search/docs/appearance/structured-data";

/** Nested-only building blocks. */
const nested: TypeDefinition[] = [
  {
    alias: "PostalAddress",
    label: "Postal address",
    description: "A street address.",
    icon: "icon-map-location",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      text("streetAddress", "Street address", { recommended: true, example: "12 Example Street" }),
      text("addressLocality", "Suburb / city", { recommended: true, example: "Newcastle" }),
      text("addressRegion", "State / region", { recommended: true, example: "NSW" }),
      text("postalCode", "Postcode", { recommended: true, example: "2300" }),
      text("addressCountry", "Country", { recommended: true, description: "Two-letter ISO code.", placeholder: "AU", example: "AU" }),
    ],
    summaryKey: "streetAddress",
  },
  {
    alias: "GeoCoordinates",
    label: "Geo coordinates",
    description: "Latitude and longitude.",
    icon: "icon-map-marker",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      number("latitude", "Latitude", { required: true, description: "Decimal degrees; south of the equator is negative.", example: "-32.9283" }),
      number("longitude", "Longitude", { required: true, description: "Decimal degrees.", example: "151.7817" }),
    ],
  },
  {
    alias: "ContactPoint",
    label: "Contact point",
    description: "A way to reach the organisation.",
    icon: "icon-phone",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      text("contactType", "Contact type", { required: true, placeholder: "customer service", description: "What this contact is for.", example: "customer service, sales, technical support" }),
      tel("telephone", "Telephone", { recommended: true, description: "Include the country code.", example: "+61 2 4000 0000" }),
      email("email", "Email", { recommended: true, example: "hello@example.com" }),
      list("areaServed", "Areas served", ofText(), { description: "Country codes, one per row.", example: "AU" }),
      list("availableLanguage", "Languages", ofText(), { example: "English" }),
    ],
    summaryKey: "contactType",
  },
  {
    alias: "OpeningHoursSpecification",
    label: "Opening hours",
    description: "Hours for a set of days.",
    icon: "icon-time",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      list("dayOfWeek", "Days", ofText({ placeholder: "Monday" }), { required: true, description: "Full English day names, one per row. Use one entry per set of days with the same hours." }),
      text("opens", "Opens", { required: true, placeholder: "09:00", description: "24-hour time.", example: "09:00" }),
      text("closes", "Closes", { required: true, placeholder: "17:00", description: "24-hour time.", example: "17:30" }),
    ],
    summaryKey: "opens",
  },
  {
    alias: "Offer",
    label: "Offer",
    description: "A price and availability.",
    icon: "icon-price",
    group: "Products & services",
    topLevel: false,
    fields: [
      number("price", "Price", { required: true, description: "Numbers only, no currency symbol.", example: "49.95" }),
      text("priceCurrency", "Currency", { required: true, placeholder: "AUD", description: "Three-letter ISO code.", example: "AUD" }),
      select(
        "availability",
        "Availability",
        options(
          ["https://schema.org/InStock", "In stock"],
          ["https://schema.org/OutOfStock", "Out of stock"],
          ["https://schema.org/PreOrder", "Pre-order"],
          ["https://schema.org/SoldOut", "Sold out"],
          ["https://schema.org/OnlineOnly", "Online only"],
          ["https://schema.org/LimitedAvailability", "Limited availability"],
        ),
        { recommended: true, description: "Keep it current; a stale availability is worse than none." },
      ),
      link("url", "Offer URL", { recommended: true, description: "Where the offer can be taken up; usually this page." }),
      date("priceValidUntil", "Price valid until", { description: "For sale prices with an end date." }),
      date("validFrom", "Valid from"),
      select("itemCondition", "Condition", options(["https://schema.org/NewCondition", "New"], ["https://schema.org/UsedCondition", "Used"], ["https://schema.org/RefurbishedCondition", "Refurbished"])),
    ],
    summaryKey: "price",
  },
  {
    alias: "AggregateRating",
    label: "Aggregate rating",
    description: "An average of many ratings.",
    icon: "icon-rate",
    group: "Products & services",
    topLevel: false,
    fields: [
      number("ratingValue", "Rating value", { required: true, description: "The average, on the scale below.", example: "4.6" }),
      number("ratingCount", "Rating count", { recommended: true, description: "How many ratings the average is based on. Give this or the review count." }),
      number("reviewCount", "Review count", { recommended: true, description: "How many written reviews." }),
      number("bestRating", "Best possible rating", { placeholder: "5", description: "Defaults to 5." }),
      number("worstRating", "Worst possible rating", { placeholder: "1", description: "Defaults to 1." }),
    ],
    summaryKey: "ratingValue",
  },
  {
    alias: "Rating",
    label: "Rating",
    description: "A single rating.",
    icon: "icon-rate",
    group: "Products & services",
    topLevel: false,
    fields: [
      number("ratingValue", "Rating value", { required: true, example: "5" }),
      number("bestRating", "Best possible rating", { placeholder: "5", description: "Defaults to 5." }),
      number("worstRating", "Worst possible rating", { placeholder: "1", description: "Defaults to 1." }),
    ],
    summaryKey: "ratingValue",
  },
  {
    alias: "MonetaryAmount",
    label: "Monetary amount",
    description: "A value in a currency.",
    icon: "icon-coins",
    group: "Products & services",
    topLevel: false,
    fields: [
      text("currency", "Currency", { required: true, placeholder: "AUD", description: "Three-letter ISO code.", example: "AUD" }),
      number("value", "Value", { recommended: true, description: "A single figure. For a range, use minimum and maximum instead.", example: "95000" }),
      number("minValue", "Minimum"),
      number("maxValue", "Maximum"),
      select("unitText", "Per", options("HOUR", "DAY", "WEEK", "MONTH", "YEAR"), { description: "The period the amount covers." }),
    ],
    summaryKey: "value",
  },
  {
    alias: "Brand",
    label: "Brand",
    description: "A brand name.",
    icon: "icon-tag",
    group: "Products & services",
    topLevel: false,
    fields: [text("name", "Name", { required: true, example: "Acme" })],
    summaryKey: "name",
  },
  {
    alias: "Question",
    label: "Question",
    description: "One FAQ entry.",
    icon: "icon-help-alt",
    group: "Pages & content",
    topLevel: false,
    fields: [
      text("name", "Question", { required: true, description: "The full question as shown on the page.", example: "Do you offer support after launch?" }),
      entity("acceptedAnswer", "Answer", ["Answer"], { required: true, inline: true }),
    ],
    summaryKey: "name",
    defaults: { acceptedAnswer: { "@type": "Answer" } },
  },
  {
    alias: "Answer",
    label: "Answer",
    description: "The accepted answer to a question.",
    icon: "icon-check",
    group: "Pages & content",
    topLevel: false,
    fields: [textarea("text", "Answer", { required: true, description: "The complete answer as shown on the page, not a summary. Plain text or simple HTML." })],
    summaryKey: "text",
  },
  {
    alias: "HowToStep",
    label: "Step",
    description: "One step of a how-to.",
    icon: "icon-ordered-list",
    group: "Pages & content",
    topLevel: false,
    fields: [
      text("name", "Step title", { recommended: true, example: "Turn off the water" }),
      textarea("text", "Instructions", { required: true, description: "What to do in this step, in full." }),
      link("url", "Link to this step", { description: "An anchor on the page, if each step has one." }),
      image("image", "Image", { description: "A photo of this step." }),
    ],
    summaryKey: "name",
  },
  {
    alias: "HowToSupply",
    label: "Supply",
    description: "Something consumed by the how-to.",
    icon: "icon-box",
    group: "Pages & content",
    topLevel: false,
    fields: [text("name", "Name", { required: true, example: "Replacement washer" })],
    summaryKey: "name",
  },
  {
    alias: "HowToTool",
    label: "Tool",
    description: "Something used but not consumed.",
    icon: "icon-wrench",
    group: "Pages & content",
    topLevel: false,
    fields: [text("name", "Name", { required: true, example: "Adjustable spanner" })],
    summaryKey: "name",
  },
  {
    alias: "ListItem",
    label: "List item",
    description: "One entry of a breadcrumb or item list.",
    icon: "icon-navigation",
    group: "Pages & content",
    topLevel: false,
    fields: [
      text("name", "Name", { required: true, description: "Exactly as shown on the page.", example: "Case studies" }),
      link("item", "Page", { recommended: true, description: "The page this entry links to. A breadcrumb's last entry can leave it off." }),
    ],
    summaryKey: "name",
  },
  {
    alias: "SearchAction",
    label: "Site search",
    description: "Tells search engines how your site search works.",
    icon: "icon-search",
    group: "Pages & content",
    topLevel: false,
    fields: [
      text("target", "Search URL template", {
        required: true,
        placeholder: "https://example.com/search?q={search_term_string}",
        description: "Your search results URL with {search_term_string} where the query goes.",
        example: "https://www.example.com/search?q={search_term_string}",
      }),
      text("query-input", "Query input", { required: true, placeholder: "required name=search_term_string", description: "Leave as is; it names the placeholder above." }),
    ],
    defaults: { "query-input": "required name=search_term_string" },
    summaryKey: "target",
  },
  {
    alias: "Place",
    label: "Place",
    description: "A physical venue.",
    icon: "icon-map-location",
    group: "Events & jobs",
    topLevel: false,
    fields: [
      text("name", "Name", { recommended: true, example: "Newcastle City Hall" }),
      entity("address", "Address", ["PostalAddress"], { required: true, inline: true }),
      url("url", "Website", { description: "The venue's own site, if it has one." }),
    ],
    summaryKey: "name",
    defaults: { address: { "@type": "PostalAddress" } },
  },
  {
    alias: "VirtualLocation",
    label: "Online location",
    description: "A URL where an online event happens.",
    icon: "icon-globe",
    group: "Events & jobs",
    topLevel: false,
    fields: [url("url", "URL", { required: true, description: "Where attendees join or watch.", example: "https://www.example.com/webinar/live" })],
    summaryKey: "url",
  },
];

const organisationFields = [
  text("name", "Name", { required: true, description: "The name customers know you by.", example: "Acme Pty Ltd" }),
  link("url", "Website", { recommended: true, description: "The home page, including https://." }),
  image("logo", "Logo", { recommended: true, description: "At least 112×112px on a plain background; square works best." }),
  textarea("description", "Description", { description: "One or two sentences on what the organisation does." }),
  list("sameAs", "Social and profile URLs", ofUrl({ placeholder: "https://" }), { recommended: true, description: "Profiles you actually maintain: LinkedIn, Instagram, Wikipedia, Crunchbase.", example: "https://www.linkedin.com/company/acme" }),
  email("email", "Email", { example: "hello@example.com" }),
  tel("telephone", "Telephone", { description: "Include the country code.", example: "+61 2 4000 0000" }),
  entity("address", "Address", ["PostalAddress"], { description: "The head office or registered address." }),
  list("contactPoint", "Contact points", ofEntity(["ContactPoint"]), { description: "One per purpose: sales, support, and so on." }),
  date("foundingDate", "Founding date"),
  number("numberOfEmployees", "Number of employees", { example: "40" }),
];

const personFields = [
  text("name", "Name", { required: true, description: "As it appears in bylines on this site.", example: "Jane Smith" }),
  text("jobTitle", "Job title", { recommended: true, example: "Head of Engineering" }),
  image("image", "Photo", { recommended: true, description: "A clear head-and-shoulders photo." }),
  link("url", "Profile page", { recommended: true, description: "This person's page on the site, or their public profile elsewhere." }),
  textarea("description", "Bio", { description: "A short professional biography." }),
  email("email", "Email"),
  tel("telephone", "Telephone"),
  list("sameAs", "Social and profile URLs", ofUrl({ placeholder: "https://" }), { recommended: true, description: "LinkedIn, GitHub, Mastodon, and the like.", example: "https://www.linkedin.com/in/janesmith" }),
  entity("worksFor", "Works for", ["Organization"], { description: "Usually your Organisation." }),
  list("knowsAbout", "Areas of expertise", ofText(), { description: "One topic per row.", example: "Umbraco" }),
];

/** Types an editor can add to a page. */
const topLevel: TypeDefinition[] = [
  {
    alias: "Organization",
    label: "Organisation",
    description: "Who is behind the site: name, logo, contact details and social profiles.",
    guidance:
      "Add one Organisation on the site root, or generate it with a site-wide rule, so it appears once on every page; do not repeat it on individual pages. Use the name customers know, a square logo on a plain background, and only the social profiles that are actually maintained.",
    icon: "icon-company",
    group: "Organisation & people",
    topLevel: true,
    fields: organisationFields,
    nestedFields: [text("name", "Name", { required: true, example: "Acme Pty Ltd" }), link("url", "Website"), image("logo", "Logo")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/organization`,
  },
  {
    alias: "LocalBusiness",
    label: "Local business",
    description: "A business with a physical location, opening hours and service area.",
    guidance:
      "For a business people visit in person. Pick the most specific variant that fits, put it on the site root or the location's own page, and fill the address, opening hours and map coordinates, which drive the map and knowledge panel results. With several locations, add one entity per location page rather than one for the company.",
    icon: "icon-store",
    group: "Organisation & people",
    topLevel: true,
    typeVariants: options(
      ["LocalBusiness", "Local business"],
      ["ProfessionalService", "Professional service"],
      ["Store", "Store"],
      ["Restaurant", "Restaurant"],
      ["MedicalBusiness", "Medical business"],
      ["FinancialService", "Financial service"],
      ["HomeAndConstructionBusiness", "Home and construction"],
    ),
    fields: [
      text("name", "Name", { required: true, description: "The trading name on the sign.", example: "Acme Plumbing Newcastle" }),
      entity("address", "Address", ["PostalAddress"], { required: true, description: "The physical premises, not a PO box." }),
      list("image", "Photos", ofImage(), { recommended: true, description: "Photos of the premises or team, at least 720px wide." }),
      link("url", "Website", { recommended: true, description: "This location's page, or the home page for a single location." }),
      tel("telephone", "Telephone", { recommended: true, description: "Include the country code.", example: "+61 2 4000 0000" }),
      email("email", "Email", { example: "hello@example.com" }),
      textarea("description", "Description", { description: "What the business does, in a sentence or two." }),
      entity("geo", "Map coordinates", ["GeoCoordinates"], { recommended: true, description: "Latitude and longitude of the entrance." }),
      list("openingHoursSpecification", "Opening hours", ofEntity(["OpeningHoursSpecification"]), { recommended: true, description: "One entry per set of days with the same hours." }),
      text("priceRange", "Price range", { placeholder: "$$", description: "From $ (cheap) to $$$$ (premium).", example: "$$" }),
      list("sameAs", "Social and profile URLs", ofUrl({ placeholder: "https://" }), { description: "Google Business Profile, Facebook, and the like." }),
      list("areaServed", "Areas served", ofText(), { description: "Place names or country codes, one per row.", example: "Newcastle, NSW" }),
    ],
    nestedFields: [text("name", "Name", { required: true }), link("url", "Website")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/local-business`,
    defaults: { address: { "@type": "PostalAddress" } },
  },
  {
    alias: "Person",
    label: "Person",
    description: "A team member, author or founder.",
    guidance:
      "For author and team profiles. Put it on the person's own profile page with a photo and a profile URL, and use exactly the same name in Article authors so the entities link up. Do not add a Person for the site's owner on every page; that is the Organisation's job.",
    icon: "icon-user",
    group: "Organisation & people",
    topLevel: true,
    fields: personFields,
    nestedFields: [text("name", "Name", { required: true, example: "Jane Smith" }), link("url", "Profile page"), text("jobTitle", "Job title", { example: "Head of Engineering" })],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/profile-page`,
  },
  {
    alias: "WebSite",
    label: "Website",
    description: "The site as a whole, with its name and site search.",
    guidance:
      "One per site, on the site root or a site-wide rule. It tells Google your preferred site name and, with a site search action, can add a search box under your result. Use the bare root URL and the short name people search for, not a slogan.",
    icon: "icon-globe",
    group: "Pages & content",
    topLevel: true,
    fields: [
      text("name", "Site name", { required: true, description: "Shown as the site name in search results.", example: "Acme" }),
      url("url", "Site URL", { required: true, placeholder: "https://", description: "The root of the site, with a trailing slash.", example: "https://www.example.com/" }),
      text("alternateName", "Alternate name", { description: "A short name or acronym search engines may show instead.", example: "ACME" }),
      textarea("description", "Description", { description: "What the site is about, in a sentence." }),
      entity("publisher", "Publisher", ["Organization"], { description: "Usually your Organisation." }),
      entity("potentialAction", "Site search", ["SearchAction"], { description: "Only if the site has a search results page with the query in its URL." }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/site-names`,
  },
  {
    alias: "WebPage",
    label: "Web page",
    description: "Describes this page itself. Most sites generate this automatically; add it to override.",
    guidance:
      "Rarely needed by hand: a site-wide rule generates it from each page's name, URL and dates. Add one to a page only to override the generated entity, for example to mark the About or Contact page with its specific variant.",
    icon: "icon-document",
    group: "Pages & content",
    topLevel: true,
    typeVariants: options(
      ["WebPage", "Web page"],
      ["AboutPage", "About page"],
      ["ContactPage", "Contact page"],
      ["CollectionPage", "Collection page"],
      ["ProfilePage", "Profile page"],
      ["FAQPage", "FAQ page (no questions)"],
    ),
    fields: [
      text("name", "Title", { required: true, description: "Usually the same as the page title.", example: "About Acme" }),
      textarea("description", "Description", { recommended: true, description: "Usually the meta description." }),
      link("url", "URL", { description: "Leave blank to use this page's own URL." }),
      image("primaryImageOfPage", "Primary image", { description: "The hero or lead image." }),
      date("datePublished", "Date published"),
      date("dateModified", "Date modified", { description: "The last meaningful content change." }),
    ],
    summaryKey: "name",
  },
  {
    alias: "Article",
    label: "Article",
    description: "A blog post, news story or long-form article.",
    guidance:
      "For blog posts and news. The headline should match the visible title; images at least 1200px wide in 16:9, 4:3 and 1:1 make it eligible for large previews; the author should be a Person with a profile page. Dates must be real publish and update times, since a wrong date can suppress the result.",
    icon: "icon-article",
    group: "Pages & content",
    topLevel: true,
    typeVariants: options(["Article", "Article"], ["BlogPosting", "Blog post"], ["NewsArticle", "News article"], ["TechArticle", "Technical article"]),
    fields: [
      text("headline", "Headline", { required: true, description: "The visible title, under 110 characters.", example: "Five things we learned upgrading to Umbraco 17" }),
      list("image", "Images", ofImage(), { recommended: true, description: "Ideally 16:9, 4:3 and 1:1 crops, each at least 1200px wide." }),
      datetime("datePublished", "Date published", { recommended: true, description: "When it first went live." }),
      datetime("dateModified", "Date modified", { recommended: true, description: "The last meaningful edit; leave equal to published if none." }),
      list("author", "Authors", ofEntity(["Person", "Organization"]), { recommended: true, description: "Who wrote it. A Person with a profile page is best; an Organisation for unsigned pieces." }),
      entity("publisher", "Publisher", ["Organization"], { description: "Usually your Organisation." }),
      textarea("description", "Description", { description: "A short summary, like the meta description." }),
      link("mainEntityOfPage", "Canonical page", { description: "The page this article lives on; leave blank to use this page." }),
      text("articleSection", "Section", { description: "The category or section name.", example: "News" }),
      text("keywords", "Keywords", { description: "Comma separated.", example: "umbraco, seo, structured data" }),
    ],
    summaryKey: "headline",
    docsUrl: `${GOOGLE}/article`,
  },
  {
    alias: "FAQPage",
    label: "FAQ",
    description: "Questions and answers shown on this page.",
    guidance:
      "Only for pages that visibly show a list of questions with answers written by the site itself, not user comments or a forum. Each answer should be the complete text on the page. Google now shows FAQ rich results mainly for government and health sites, but the markup still helps search engines understand the page.",
    icon: "icon-help-alt",
    group: "Pages & content",
    topLevel: true,
    fields: [list("mainEntity", "Questions", ofEntity(["Question"]), { required: true, min: 1, description: "One entry per question shown on the page, with its full answer." })],
    summaryKey: "mainEntity",
    docsUrl: `${GOOGLE}/faqpage`,
  },
  {
    alias: "HowTo",
    label: "How-to",
    description: "Step-by-step instructions.",
    guidance:
      "For instructions a reader follows in order to reach a result, not for recipes or general advice. Give every step its own text and, where you can, an image. Google retired the how-to rich result in 2023, so treat this as helping search engines understand the page rather than as a visible enhancement.",
    icon: "icon-ordered-list",
    group: "Pages & content",
    topLevel: true,
    fields: [
      text("name", "Title", { required: true, description: "What the reader will have done.", example: "How to replace a tap washer" }),
      textarea("description", "Description", { description: "What the how-to covers, in a sentence." }),
      list("step", "Steps", ofEntity(["HowToStep"]), { required: true, min: 1, autoPosition: true, description: "In order. Position numbers are added for you." }),
      image("image", "Image", { recommended: true, description: "The finished result." }),
      duration("totalTime", "Total time", { description: "ISO 8601 duration.", placeholder: "PT30M", example: "PT30M for 30 minutes, PT1H30M for an hour and a half" }),
      entity("estimatedCost", "Estimated cost", ["MonetaryAmount"], { description: "Materials only." }),
      list("supply", "Supplies", ofEntity(["HowToSupply"]), { description: "Things used up." }),
      list("tool", "Tools", ofEntity(["HowToTool"]), { description: "Things used but kept." }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/how-to`,
  },
  {
    alias: "BreadcrumbList",
    label: "Breadcrumb",
    description: "The page's position in the site hierarchy.",
    guidance:
      "Usually generated by a rule from the page's ancestors; author it by hand only when the visible breadcrumb differs from the content tree. Order the trail from the home page down to this page and use the names shown on the page.",
    icon: "icon-navigation",
    group: "Pages & content",
    topLevel: true,
    fields: [list("itemListElement", "Trail", ofEntity(["ListItem"]), { required: true, min: 1, autoPosition: true, description: "From the home page down to this page. Position numbers are added for you." })],
    summaryKey: "itemListElement",
    docsUrl: `${GOOGLE}/breadcrumb`,
  },
  {
    alias: "Service",
    label: "Service",
    description: "A service the organisation offers.",
    guidance:
      "One entity per service page, named the way the service is marketed. Set the provider to your Organisation and, for location-bound services, the areas served. There is no dedicated rich result; the value is in connecting each service to the business that provides it.",
    icon: "icon-handshake",
    group: "Products & services",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true, description: "The service as marketed.", example: "Umbraco support and maintenance" }),
      textarea("description", "Description", { recommended: true, description: "What the service includes, in a sentence or two." }),
      text("serviceType", "Service type", { recommended: true, description: "A short category for the service.", example: "Website maintenance" }),
      entity("provider", "Provider", ["Organization", "LocalBusiness"], { recommended: true, description: "Usually your Organisation." }),
      list("areaServed", "Areas served", ofText(), { description: "Place names or country codes, one per row.", example: "Australia" }),
      link("url", "Service page", { description: "Leave blank to use this page." }),
      image("image", "Image", { description: "An image representing the service." }),
      entity("offers", "Offer", ["Offer"], { description: "Only if the service has a fixed, public price." }),
    ],
    nestedFields: [text("name", "Name", { required: true }), link("url", "Service page")],
    summaryKey: "name",
  },
  {
    alias: "Product",
    label: "Product",
    description: "Something for sale, with price, availability and ratings.",
    guidance:
      "For a page about one product. It needs an offer with price and currency, or a rating, to be eligible for the product snippet. Images should show the product itself, not logos or placeholders. Add the SKU or GTIN if you have them so the product can be matched to your catalogue.",
    icon: "icon-shopping-basket",
    group: "Products & services",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true, description: "The product name as sold.", example: "Acme 1200W cordless drill" }),
      list("image", "Images", ofImage(), { recommended: true, description: "Photos of the product itself, at least 800px wide." }),
      textarea("description", "Description", { recommended: true }),
      entity("brand", "Brand", ["Brand", "Organization"], { description: "The maker's brand, which may be your own Organisation." }),
      text("sku", "SKU", { description: "Your internal product code.", example: "ACM-DRL-1200" }),
      text("mpn", "MPN", { description: "The manufacturer part number." }),
      text("gtin", "GTIN", { description: "The barcode: EAN, UPC or ISBN, digits only.", example: "9312345678907" }),
      list("offers", "Offers", ofEntity(["Offer"]), { recommended: true, description: "Price and availability. Needed for the price to show in results." }),
      entity("aggregateRating", "Aggregate rating", ["AggregateRating"], { description: "Only when the ratings are real and were collected on this site." }),
      list("review", "Reviews", ofEntity(["Review"]), { description: "Individual reviews shown on the page." }),
    ],
    nestedFields: [text("name", "Name", { required: true }), link("url", "Product page")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/product`,
  },
  {
    alias: "Review",
    label: "Review",
    description: "A single review of a product, service or business.",
    guidance:
      "A review written by someone else about the thing this page is about. Do not use it for testimonials about your own organisation or for reviews you wrote; Google ignores self-serving reviews. For many reviews, use an Aggregate rating on the Product or Local business instead.",
    icon: "icon-rate",
    group: "Products & services",
    topLevel: true,
    fields: [
      entity("itemReviewed", "Item reviewed", ["Organization", "LocalBusiness", "Product", "Service"], { required: true, description: "What was reviewed; usually the thing this page is about." }),
      entity("reviewRating", "Rating", ["Rating"], { required: true, inline: true }),
      entity("author", "Author", ["Person", "Organization"], { required: true, description: "The reviewer, not your organisation." }),
      textarea("reviewBody", "Review text", { recommended: true, description: "The review as written." }),
      date("datePublished", "Date published"),
    ],
    nestedFields: [
      entity("reviewRating", "Rating", ["Rating"], { required: true }),
      entity("author", "Author", ["Person", "Organization"], { required: true, description: "The reviewer." }),
      textarea("reviewBody", "Review text"),
      date("datePublished", "Date published"),
    ],
    summaryKey: "reviewBody",
    docsUrl: `${GOOGLE}/review-snippet`,
    defaults: { reviewRating: { "@type": "Rating" }, author: { "@type": "Person" } },
  },
  {
    alias: "SoftwareApplication",
    label: "Software application",
    description: "An app or SaaS product.",
    guidance:
      "For an app or SaaS product page. Include the operating system and category, and either a price (0 for free) or a rating; without one of those there is no rich result.",
    icon: "icon-laptop",
    group: "Products & services",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true, example: "Acme Field Notes" }),
      text("operatingSystem", "Operating system", { recommended: true, placeholder: "Web, iOS, Android", description: "Comma separated.", example: "Web, iOS, Android" }),
      select(
        "applicationCategory",
        "Category",
        options("BusinessApplication", "DeveloperApplication", "EducationalApplication", "FinanceApplication", "HealthApplication", "LifestyleApplication", "MultimediaApplication", "ProductivityApplication", "UtilitiesApplication"),
        { recommended: true },
      ),
      entity("offers", "Offer", ["Offer"], { recommended: true, description: "Use a price of 0 for a free app." }),
      entity("aggregateRating", "Aggregate rating", ["AggregateRating"], { recommended: true, description: "Only from ratings collected on this site." }),
      textarea("description", "Description"),
      link("url", "Product page", { description: "Leave blank to use this page." }),
      image("image", "Image", { description: "An icon or screenshot." }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/software-app`,
  },
  {
    alias: "Event",
    label: "Event",
    description: "A webinar, conference, launch or meetup.",
    guidance:
      "One entity per event page, with real start and end times in the venue's time zone. Choose the attendance mode, and if plans change update the status to postponed or cancelled rather than deleting the entity, so the change reaches search results too.",
    icon: "icon-calendar",
    group: "Events & jobs",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true, description: "The event's own name, not the venue's.", example: "Umbraco Meetup Newcastle: October" }),
      datetime("startDate", "Starts", { required: true, description: "Local time at the venue, including the time of day." }),
      datetime("endDate", "Ends", { recommended: true }),
      entity("location", "Location", ["Place", "VirtualLocation"], { required: true, description: "A venue with an address, or a URL for an online event." }),
      textarea("description", "Description", { recommended: true }),
      list("image", "Images", ofImage(), { recommended: true, description: "At least 720px wide." }),
      select(
        "eventAttendanceMode",
        "Attendance",
        options(
          ["https://schema.org/OfflineEventAttendanceMode", "In person"],
          ["https://schema.org/OnlineEventAttendanceMode", "Online"],
          ["https://schema.org/MixedEventAttendanceMode", "Hybrid"],
        ),
        { recommended: true },
      ),
      select(
        "eventStatus",
        "Status",
        options(
          ["https://schema.org/EventScheduled", "Scheduled"],
          ["https://schema.org/EventPostponed", "Postponed"],
          ["https://schema.org/EventRescheduled", "Rescheduled"],
          ["https://schema.org/EventMovedOnline", "Moved online"],
          ["https://schema.org/EventCancelled", "Cancelled"],
        ),
        { recommended: true, description: "Update this rather than removing the entity when plans change." },
      ),
      entity("organizer", "Organiser", ["Organization", "Person"], { recommended: true, description: "Usually your Organisation." }),
      list("performer", "Performers / speakers", ofEntity(["Person", "Organization"])),
      list("offers", "Tickets", ofEntity(["Offer"]), { description: "Ticket price and where to buy; use 0 for free events." }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/event`,
    defaults: { eventStatus: "https://schema.org/EventScheduled" },
  },
  {
    alias: "JobPosting",
    label: "Job posting",
    description: "An open role.",
    guidance:
      "One entity per vacancy page. The description must be the full listing as shown on the page, and the posting needs a closing date or must be removed once the role is filled; expired postings can cost the whole site its job eligibility.",
    icon: "icon-users",
    group: "Events & jobs",
    topLevel: true,
    fields: [
      text("title", "Job title", { required: true, description: "The role title only, without location, salary or company.", example: "Senior Umbraco developer" }),
      textarea("description", "Description", { required: true, description: "The full listing as shown on the page; HTML is allowed." }),
      date("datePosted", "Date posted", { required: true }),
      date("validThrough", "Closes", { recommended: true, description: "The closing date. The posting counts as expired after it." }),
      entity("hiringOrganization", "Hiring organisation", ["Organization"], { required: true, description: "The employer, not the recruiter, unless you are the recruiter." }),
      entity("jobLocation", "Location", ["Place"], { required: true, description: "The workplace address, even for hybrid roles." }),
      list("employmentType", "Employment type", ofText({ placeholder: "FULL_TIME" }), { recommended: true, description: "One per row from: FULL_TIME, PART_TIME, CONTRACTOR, TEMPORARY, INTERN, VOLUNTEER, PER_DIEM, OTHER.", example: "FULL_TIME" }),
      entity("baseSalary", "Base salary", ["MonetaryAmount"], { recommended: true, description: "The actual pay or a realistic range, with the period." }),
      select("jobLocationType", "Remote?", options(["TELECOMMUTE", "Fully remote"]), { description: "Only for roles done entirely from home." }),
      boolean("directApply", "Applications taken on this site", { description: "On when candidates can apply here rather than on a job board." }),
      text("identifier", "Reference", { description: "Your internal vacancy reference.", example: "REQ-1042" }),
    ],
    summaryKey: "title",
    docsUrl: `${GOOGLE}/job-posting`,
    defaults: { hiringOrganization: { "@type": "Organization" }, jobLocation: { "@type": "Place", address: { "@type": "PostalAddress" } } },
  },
  {
    alias: "VideoObject",
    label: "Video",
    description: "A video embedded on this page.",
    guidance:
      "For a page whose main content includes a video. Thumbnails, upload date and description are all required for the video result. Use the player's embed URL and, if you host the file yourself, its direct URL.",
    icon: "icon-video",
    group: "Media",
    topLevel: true,
    fields: [
      text("name", "Title", { required: true, example: "Acme Field Notes in two minutes" }),
      textarea("description", "Description", { required: true, description: "What the video shows, in a sentence or two." }),
      list("thumbnailUrl", "Thumbnails", ofImage({ as: "url" }), { required: true, description: "At least 60×30px; 16:9 works best." }),
      datetime("uploadDate", "Upload date", { required: true, description: "When the video was first published." }),
      duration("duration", "Duration", { recommended: true, description: "ISO 8601 duration.", placeholder: "PT1M30S", example: "PT1M30S for a minute and a half" }),
      url("contentUrl", "Video file URL", { recommended: true, description: "A direct link to the video file, if you host it." }),
      url("embedUrl", "Embed URL", { recommended: true, description: "The player URL.", example: "https://www.youtube.com/embed/abc123" }),
      entity("publisher", "Publisher", ["Organization"], { description: "Usually your Organisation." }),
      number("interactionCount", "View count"),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/video`,
  },
  {
    alias: "ImageObject",
    label: "Image",
    description: "A key image on the page, with credit and licence.",
    guidance:
      "For a page's key image when credit and licensing matter, such as photography, artwork or stock imagery. Google shows the licence link and credit in image results.",
    icon: "icon-picture",
    group: "Media",
    topLevel: true,
    fields: [
      image("contentUrl", "Image", { required: true, as: "url" }),
      text("name", "Title", { example: "Newcastle harbour at dawn" }),
      text("creditText", "Credit", { recommended: true, description: "Who to credit.", example: "Photo: Jane Smith" }),
      url("license", "Licence URL", { recommended: true, description: "A page stating the licence terms.", example: "https://creativecommons.org/licenses/by/4.0/" }),
      url("acquireLicensePage", "Where to licence it", { description: "Where someone can buy or request a licence." }),
      entity("creator", "Creator", ["Person", "Organization"], { description: "The photographer or artist." }),
      text("copyrightNotice", "Copyright notice", { example: "© 2026 Acme Pty Ltd" }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/image-license-metadata`,
  },
  {
    alias: "ItemList",
    label: "Item list",
    description: "An ordered list of pages, such as a listing's contents.",
    guidance:
      "For listing pages: a category, a series, a set of related pages. One item per listed page with its name and URL, in the order shown. A rule using the page's children generates this without any editing.",
    icon: "icon-bulleted-list",
    group: "Other",
    topLevel: true,
    fields: [
      text("name", "Name", { description: "What the list is.", example: "Case studies" }),
      list("itemListElement", "Items", ofEntity(["ListItem"]), { required: true, min: 1, autoPosition: true, description: "One per page shown, in order. Position numbers are added for you." }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/carousel`,
  },
];

export const catalogue: readonly TypeDefinition[] = [...topLevel, ...nested];

const byAlias = new Map(catalogue.map((definition) => [definition.alias, definition]));

/** Variants share their family's definition: `BlogPosting` resolves to the Article definition. */
const byVariant = new Map<string, TypeDefinition>();
for (const definition of catalogue) {
  for (const variant of definition.typeVariants ?? []) {
    if (!byVariant.has(variant.value)) byVariant.set(variant.value, definition);
  }
}

export function getDefinition(alias: string): TypeDefinition | undefined {
  return byAlias.get(alias) ?? byVariant.get(alias);
}

export function topLevelDefinitions(): TypeDefinition[] {
  return catalogue.filter((definition) => definition.topLevel);
}

export const groupOrder: readonly string[] = ["Pages & content", "Organisation & people", "Products & services", "Events & jobs", "Media", "Other"];
