import type { TypeDefinition } from "./types.js";
import {
  boolean,
  date,
  datetime,
  document,
  duration,
  email,
  entity,
  image,
  link,
  list,
  number,
  ofEntity,
  ofImage,
  ofLink,
  ofText,
  ofUrl,
  options,
  select,
  tel,
  text,
  textarea,
  url,
} from "./fields.js";

export type * from "./types.js";

const GOOGLE = "https://developers.google.com/search/docs/appearance/structured-data";

/** Nested-only building blocks. */
const nested: TypeDefinition[] = [
  {
    alias: "PostalAddress",
    label: "Postal address",
    description: "A street address.",
    icon: "icon-map-location",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      text("streetAddress", "Street address", { recommended: true }),
      text("addressLocality", "Suburb / city", { recommended: true }),
      text("addressRegion", "State / region", { recommended: true }),
      text("postalCode", "Postcode", { recommended: true }),
      text("addressCountry", "Country", { recommended: true, description: "Two-letter ISO code, for example AU.", placeholder: "AU" }),
    ],
    summaryKey: "streetAddress",
  },
  {
    alias: "GeoCoordinates",
    label: "Geo coordinates",
    description: "Latitude and longitude.",
    icon: "icon-map-marker",
    group: "Organisation & people",
    topLevel: false,
    fields: [number("latitude", "Latitude", { required: true }), number("longitude", "Longitude", { required: true })],
  },
  {
    alias: "ContactPoint",
    label: "Contact point",
    description: "A way to reach the organisation.",
    icon: "icon-phone",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      text("contactType", "Contact type", { required: true, placeholder: "customer service", description: "For example customer service, sales, technical support." }),
      tel("telephone", "Telephone", { recommended: true }),
      email("email", "Email", { recommended: true }),
      list("areaServed", "Areas served", ofText(), { description: "Country codes, for example AU." }),
      list("availableLanguage", "Languages", ofText()),
    ],
    summaryKey: "contactType",
  },
  {
    alias: "OpeningHoursSpecification",
    label: "Opening hours",
    description: "Hours for a set of days.",
    icon: "icon-time",
    group: "Organisation & people",
    topLevel: false,
    fields: [
      list("dayOfWeek", "Days", ofText({ placeholder: "Monday" }), { required: true, description: "Full English day names, one per row." }),
      text("opens", "Opens", { required: true, placeholder: "09:00" }),
      text("closes", "Closes", { required: true, placeholder: "17:00" }),
    ],
    summaryKey: "opens",
  },
  {
    alias: "Offer",
    label: "Offer",
    description: "A price and availability.",
    icon: "icon-price",
    group: "Products & services",
    topLevel: false,
    fields: [
      number("price", "Price", { required: true }),
      text("priceCurrency", "Currency", { required: true, placeholder: "AUD", description: "Three-letter ISO code." }),
      select(
        "availability",
        "Availability",
        options(
          ["https://schema.org/InStock", "In stock"],
          ["https://schema.org/OutOfStock", "Out of stock"],
          ["https://schema.org/PreOrder", "Pre-order"],
          ["https://schema.org/SoldOut", "Sold out"],
          ["https://schema.org/OnlineOnly", "Online only"],
          ["https://schema.org/LimitedAvailability", "Limited availability"],
        ),
        { recommended: true },
      ),
      link("url", "Offer URL", { recommended: true }),
      date("priceValidUntil", "Price valid until"),
      date("validFrom", "Valid from"),
      select("itemCondition", "Condition", options(["https://schema.org/NewCondition", "New"], ["https://schema.org/UsedCondition", "Used"], ["https://schema.org/RefurbishedCondition", "Refurbished"])),
    ],
    summaryKey: "price",
  },
  {
    alias: "AggregateRating",
    label: "Aggregate rating",
    description: "An average of many ratings.",
    icon: "icon-rate",
    group: "Products & services",
    topLevel: false,
    fields: [
      number("ratingValue", "Rating value", { required: true }),
      number("ratingCount", "Rating count", { recommended: true }),
      number("reviewCount", "Review count", { recommended: true }),
      number("bestRating", "Best possible rating", { placeholder: "5" }),
      number("worstRating", "Worst possible rating", { placeholder: "1" }),
    ],
    summaryKey: "ratingValue",
  },
  {
    alias: "Rating",
    label: "Rating",
    description: "A single rating.",
    icon: "icon-rate",
    group: "Products & services",
    topLevel: false,
    fields: [
      number("ratingValue", "Rating value", { required: true }),
      number("bestRating", "Best possible rating", { placeholder: "5" }),
      number("worstRating", "Worst possible rating", { placeholder: "1" }),
    ],
    summaryKey: "ratingValue",
  },
  {
    alias: "MonetaryAmount",
    label: "Monetary amount",
    description: "A value in a currency.",
    icon: "icon-coins",
    group: "Products & services",
    topLevel: false,
    fields: [
      text("currency", "Currency", { required: true, placeholder: "AUD" }),
      number("value", "Value", { recommended: true }),
      number("minValue", "Minimum"),
      number("maxValue", "Maximum"),
      select("unitText", "Per", options("HOUR", "DAY", "WEEK", "MONTH", "YEAR")),
    ],
    summaryKey: "value",
  },
  {
    alias: "Brand",
    label: "Brand",
    description: "A brand name.",
    icon: "icon-tag",
    group: "Products & services",
    topLevel: false,
    fields: [text("name", "Name", { required: true })],
    summaryKey: "name",
  },
  {
    alias: "Question",
    label: "Question",
    description: "One FAQ entry.",
    icon: "icon-help-alt",
    group: "Pages & content",
    topLevel: false,
    fields: [text("name", "Question", { required: true }), entity("acceptedAnswer", "Answer", ["Answer"], { required: true, inline: true })],
    summaryKey: "name",
    defaults: { acceptedAnswer: { "@type": "Answer" } },
  },
  {
    alias: "Answer",
    label: "Answer",
    description: "The accepted answer to a question.",
    icon: "icon-check",
    group: "Pages & content",
    topLevel: false,
    fields: [textarea("text", "Answer", { required: true, description: "Plain text or simple HTML." })],
    summaryKey: "text",
  },
  {
    alias: "HowToStep",
    label: "Step",
    description: "One step of a how-to.",
    icon: "icon-ordered-list",
    group: "Pages & content",
    topLevel: false,
    fields: [
      text("name", "Step title", { recommended: true }),
      textarea("text", "Instructions", { required: true }),
      link("url", "Link to this step"),
      image("image", "Image"),
    ],
    summaryKey: "name",
  },
  {
    alias: "HowToSupply",
    label: "Supply",
    description: "Something consumed by the how-to.",
    icon: "icon-box",
    group: "Pages & content",
    topLevel: false,
    fields: [text("name", "Name", { required: true })],
    summaryKey: "name",
  },
  {
    alias: "HowToTool",
    label: "Tool",
    description: "Something used but not consumed.",
    icon: "icon-wrench",
    group: "Pages & content",
    topLevel: false,
    fields: [text("name", "Name", { required: true })],
    summaryKey: "name",
  },
  {
    alias: "ListItem",
    label: "List item",
    description: "One entry of a breadcrumb or item list.",
    icon: "icon-navigation",
    group: "Pages & content",
    topLevel: false,
    fields: [text("name", "Name", { required: true }), link("item", "Page", { recommended: true })],
    summaryKey: "name",
  },
  {
    alias: "SearchAction",
    label: "Site search",
    description: "Tells search engines how your site search works.",
    icon: "icon-search",
    group: "Pages & content",
    topLevel: false,
    fields: [
      text("target", "Search URL template", { required: true, placeholder: "https://example.com/search?q={search_term_string}" }),
      text("query-input", "Query input", { required: true, placeholder: "required name=search_term_string" }),
    ],
    defaults: { "query-input": "required name=search_term_string" },
    summaryKey: "target",
  },
  {
    alias: "Place",
    label: "Place",
    description: "A physical venue.",
    icon: "icon-map-location",
    group: "Events & jobs",
    topLevel: false,
    fields: [text("name", "Name", { recommended: true }), entity("address", "Address", ["PostalAddress"], { required: true, inline: true }), url("url", "Website")],
    summaryKey: "name",
    defaults: { address: { "@type": "PostalAddress" } },
  },
  {
    alias: "VirtualLocation",
    label: "Online location",
    description: "A URL where an online event happens.",
    icon: "icon-globe",
    group: "Events & jobs",
    topLevel: false,
    fields: [url("url", "URL", { required: true })],
    summaryKey: "url",
  },
];

const organisationFields = [
  text("name", "Name", { required: true }),
  link("url", "Website", { recommended: true }),
  image("logo", "Logo", { recommended: true, description: "At least 112×112px on a plain background." }),
  textarea("description", "Description"),
  list("sameAs", "Social and profile URLs", ofUrl({ placeholder: "https://" }), { recommended: true, description: "LinkedIn, Instagram, Wikipedia, Crunchbase…" }),
  email("email", "Email"),
  tel("telephone", "Telephone"),
  entity("address", "Address", ["PostalAddress"]),
  list("contactPoint", "Contact points", ofEntity(["ContactPoint"])),
  date("foundingDate", "Founding date"),
  number("numberOfEmployees", "Number of employees"),
];

const personFields = [
  text("name", "Name", { required: true }),
  text("jobTitle", "Job title", { recommended: true }),
  image("image", "Photo", { recommended: true }),
  link("url", "Profile page", { recommended: true }),
  textarea("description", "Bio"),
  email("email", "Email"),
  tel("telephone", "Telephone"),
  list("sameAs", "Social and profile URLs", ofUrl({ placeholder: "https://" }), { recommended: true }),
  entity("worksFor", "Works for", ["Organization"]),
  list("knowsAbout", "Areas of expertise", ofText()),
];

/** Types an editor can add to a page. */
const topLevel: TypeDefinition[] = [
  {
    alias: "Organization",
    label: "Organisation",
    description: "Who is behind the site: name, logo, contact details and social profiles.",
    icon: "icon-company",
    group: "Organisation & people",
    topLevel: true,
    fields: organisationFields,
    nestedFields: [text("name", "Name", { required: true }), link("url", "Website"), image("logo", "Logo")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/organization`,
  },
  {
    alias: "LocalBusiness",
    label: "Local business",
    description: "A business with a physical location, opening hours and service area.",
    icon: "icon-store",
    group: "Organisation & people",
    topLevel: true,
    typeVariants: options(
      ["LocalBusiness", "Local business"],
      ["ProfessionalService", "Professional service"],
      ["Store", "Store"],
      ["Restaurant", "Restaurant"],
      ["MedicalBusiness", "Medical business"],
      ["FinancialService", "Financial service"],
      ["HomeAndConstructionBusiness", "Home and construction"],
    ),
    fields: [
      text("name", "Name", { required: true }),
      entity("address", "Address", ["PostalAddress"], { required: true }),
      list("image", "Photos", ofImage(), { recommended: true }),
      link("url", "Website", { recommended: true }),
      tel("telephone", "Telephone", { recommended: true }),
      email("email", "Email"),
      textarea("description", "Description"),
      entity("geo", "Map coordinates", ["GeoCoordinates"], { recommended: true }),
      list("openingHoursSpecification", "Opening hours", ofEntity(["OpeningHoursSpecification"]), { recommended: true }),
      text("priceRange", "Price range", { placeholder: "$$" }),
      list("sameAs", "Social and profile URLs", ofUrl({ placeholder: "https://" })),
      list("areaServed", "Areas served", ofText()),
    ],
    nestedFields: [text("name", "Name", { required: true }), link("url", "Website")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/local-business`,
    defaults: { address: { "@type": "PostalAddress" } },
  },
  {
    alias: "Person",
    label: "Person",
    description: "A team member, author or founder.",
    icon: "icon-user",
    group: "Organisation & people",
    topLevel: true,
    fields: personFields,
    nestedFields: [text("name", "Name", { required: true }), link("url", "Profile page"), text("jobTitle", "Job title")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/profile-page`,
  },
  {
    alias: "WebSite",
    label: "Website",
    description: "The site as a whole, with its name and site search.",
    icon: "icon-globe",
    group: "Pages & content",
    topLevel: true,
    fields: [
      text("name", "Site name", { required: true }),
      url("url", "Site URL", { required: true, placeholder: "https://" }),
      text("alternateName", "Alternate name", { description: "A short name or acronym search engines may show." }),
      textarea("description", "Description"),
      entity("publisher", "Publisher", ["Organization"]),
      entity("potentialAction", "Site search", ["SearchAction"]),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/site-names`,
  },
  {
    alias: "WebPage",
    label: "Web page",
    description: "Describes this page itself. Most sites generate this automatically; add it to override.",
    icon: "icon-document",
    group: "Pages & content",
    topLevel: true,
    typeVariants: options(
      ["WebPage", "Web page"],
      ["AboutPage", "About page"],
      ["ContactPage", "Contact page"],
      ["CollectionPage", "Collection page"],
      ["ProfilePage", "Profile page"],
      ["FAQPage", "FAQ page (no questions)"],
    ),
    fields: [
      text("name", "Title", { required: true }),
      textarea("description", "Description", { recommended: true }),
      link("url", "URL"),
      image("primaryImageOfPage", "Primary image"),
      date("datePublished", "Date published"),
      date("dateModified", "Date modified"),
    ],
    summaryKey: "name",
  },
  {
    alias: "Article",
    label: "Article",
    description: "A blog post, news story or long-form article.",
    icon: "icon-article",
    group: "Pages & content",
    topLevel: true,
    typeVariants: options(["Article", "Article"], ["BlogPosting", "Blog post"], ["NewsArticle", "News article"], ["TechArticle", "Technical article"]),
    fields: [
      text("headline", "Headline", { required: true, description: "Under 110 characters." }),
      list("image", "Images", ofImage(), { recommended: true, description: "Ideally 16:9, 4:3 and 1:1 crops, each at least 1200px wide." }),
      datetime("datePublished", "Date published", { recommended: true }),
      datetime("dateModified", "Date modified", { recommended: true }),
      list("author", "Authors", ofEntity(["Person", "Organization"]), { recommended: true }),
      entity("publisher", "Publisher", ["Organization"]),
      textarea("description", "Description"),
      link("mainEntityOfPage", "Canonical page"),
      text("articleSection", "Section"),
      text("keywords", "Keywords", { description: "Comma separated." }),
    ],
    summaryKey: "headline",
    docsUrl: `${GOOGLE}/article`,
  },
  {
    alias: "FAQPage",
    label: "FAQ",
    description: "Questions and answers shown on this page.",
    icon: "icon-help-alt",
    group: "Pages & content",
    topLevel: true,
    fields: [list("mainEntity", "Questions", ofEntity(["Question"]), { required: true, min: 1 })],
    summaryKey: "mainEntity",
    docsUrl: `${GOOGLE}/faqpage`,
  },
  {
    alias: "HowTo",
    label: "How-to",
    description: "Step-by-step instructions.",
    icon: "icon-ordered-list",
    group: "Pages & content",
    topLevel: true,
    fields: [
      text("name", "Title", { required: true }),
      textarea("description", "Description"),
      list("step", "Steps", ofEntity(["HowToStep"]), { required: true, min: 1, autoPosition: true }),
      image("image", "Image", { recommended: true }),
      duration("totalTime", "Total time", { description: "ISO 8601 duration, for example PT30M.", placeholder: "PT30M" }),
      entity("estimatedCost", "Estimated cost", ["MonetaryAmount"]),
      list("supply", "Supplies", ofEntity(["HowToSupply"])),
      list("tool", "Tools", ofEntity(["HowToTool"])),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/how-to`,
  },
  {
    alias: "BreadcrumbList",
    label: "Breadcrumb",
    description: "The page's position in the site hierarchy.",
    icon: "icon-navigation",
    group: "Pages & content",
    topLevel: true,
    fields: [list("itemListElement", "Trail", ofEntity(["ListItem"]), { required: true, min: 1, autoPosition: true, description: "From the home page down to this page." })],
    summaryKey: "itemListElement",
    docsUrl: `${GOOGLE}/breadcrumb`,
  },
  {
    alias: "Service",
    label: "Service",
    description: "A service the organisation offers.",
    icon: "icon-handshake",
    group: "Products & services",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true }),
      textarea("description", "Description", { recommended: true }),
      text("serviceType", "Service type", { recommended: true }),
      entity("provider", "Provider", ["Organization", "LocalBusiness"], { recommended: true }),
      list("areaServed", "Areas served", ofText()),
      link("url", "Service page"),
      image("image", "Image"),
      entity("offers", "Offer", ["Offer"]),
    ],
    nestedFields: [text("name", "Name", { required: true }), link("url", "Service page")],
    summaryKey: "name",
  },
  {
    alias: "Product",
    label: "Product",
    description: "Something for sale, with price, availability and ratings.",
    icon: "icon-shopping-basket",
    group: "Products & services",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true }),
      list("image", "Images", ofImage(), { recommended: true }),
      textarea("description", "Description", { recommended: true }),
      entity("brand", "Brand", ["Brand", "Organization"]),
      text("sku", "SKU"),
      text("mpn", "MPN"),
      text("gtin", "GTIN"),
      list("offers", "Offers", ofEntity(["Offer"]), { recommended: true }),
      entity("aggregateRating", "Aggregate rating", ["AggregateRating"]),
      list("review", "Reviews", ofEntity(["Review"])),
    ],
    nestedFields: [text("name", "Name", { required: true }), link("url", "Product page")],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/product`,
  },
  {
    alias: "Review",
    label: "Review",
    description: "A single review of a product, service or business.",
    icon: "icon-rate",
    group: "Products & services",
    topLevel: true,
    fields: [
      entity("itemReviewed", "Item reviewed", ["Organization", "LocalBusiness", "Product", "Service"], { required: true }),
      entity("reviewRating", "Rating", ["Rating"], { required: true, inline: true }),
      entity("author", "Author", ["Person", "Organization"], { required: true }),
      textarea("reviewBody", "Review text", { recommended: true }),
      date("datePublished", "Date published"),
    ],
    nestedFields: [
      entity("reviewRating", "Rating", ["Rating"], { required: true }),
      entity("author", "Author", ["Person", "Organization"], { required: true }),
      textarea("reviewBody", "Review text"),
      date("datePublished", "Date published"),
    ],
    summaryKey: "reviewBody",
    docsUrl: `${GOOGLE}/review-snippet`,
    defaults: { reviewRating: { "@type": "Rating" }, author: { "@type": "Person" } },
  },
  {
    alias: "SoftwareApplication",
    label: "Software application",
    description: "An app or SaaS product.",
    icon: "icon-laptop",
    group: "Products & services",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true }),
      text("operatingSystem", "Operating system", { recommended: true, placeholder: "Web, iOS, Android" }),
      select(
        "applicationCategory",
        "Category",
        options("BusinessApplication", "DeveloperApplication", "EducationalApplication", "FinanceApplication", "HealthApplication", "LifestyleApplication", "MultimediaApplication", "ProductivityApplication", "UtilitiesApplication"),
        { recommended: true },
      ),
      entity("offers", "Offer", ["Offer"], { recommended: true }),
      entity("aggregateRating", "Aggregate rating", ["AggregateRating"], { recommended: true }),
      textarea("description", "Description"),
      link("url", "Product page"),
      image("image", "Image"),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/software-app`,
  },
  {
    alias: "Event",
    label: "Event",
    description: "A webinar, conference, launch or meetup.",
    icon: "icon-calendar",
    group: "Events & jobs",
    topLevel: true,
    fields: [
      text("name", "Name", { required: true }),
      datetime("startDate", "Starts", { required: true }),
      datetime("endDate", "Ends", { recommended: true }),
      entity("location", "Location", ["Place", "VirtualLocation"], { required: true }),
      textarea("description", "Description", { recommended: true }),
      list("image", "Images", ofImage(), { recommended: true }),
      select(
        "eventAttendanceMode",
        "Attendance",
        options(
          ["https://schema.org/OfflineEventAttendanceMode", "In person"],
          ["https://schema.org/OnlineEventAttendanceMode", "Online"],
          ["https://schema.org/MixedEventAttendanceMode", "Hybrid"],
        ),
        { recommended: true },
      ),
      select(
        "eventStatus",
        "Status",
        options(
          ["https://schema.org/EventScheduled", "Scheduled"],
          ["https://schema.org/EventPostponed", "Postponed"],
          ["https://schema.org/EventRescheduled", "Rescheduled"],
          ["https://schema.org/EventMovedOnline", "Moved online"],
          ["https://schema.org/EventCancelled", "Cancelled"],
        ),
        { recommended: true },
      ),
      entity("organizer", "Organiser", ["Organization", "Person"], { recommended: true }),
      list("performer", "Performers / speakers", ofEntity(["Person", "Organization"])),
      list("offers", "Tickets", ofEntity(["Offer"])),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/event`,
    defaults: { eventStatus: "https://schema.org/EventScheduled" },
  },
  {
    alias: "JobPosting",
    label: "Job posting",
    description: "An open role.",
    icon: "icon-users",
    group: "Events & jobs",
    topLevel: true,
    fields: [
      text("title", "Job title", { required: true }),
      textarea("description", "Description", { required: true, description: "The full listing; HTML is allowed." }),
      date("datePosted", "Date posted", { required: true }),
      date("validThrough", "Closes", { recommended: true }),
      entity("hiringOrganization", "Hiring organisation", ["Organization"], { required: true }),
      entity("jobLocation", "Location", ["Place"], { required: true }),
      list("employmentType", "Employment type", ofText({ placeholder: "FULL_TIME" }), { recommended: true, description: "FULL_TIME, PART_TIME, CONTRACTOR, TEMPORARY, INTERN, VOLUNTEER, PER_DIEM, OTHER." }),
      entity("baseSalary", "Base salary", ["MonetaryAmount"], { recommended: true }),
      select("jobLocationType", "Remote?", options(["TELECOMMUTE", "Fully remote"])),
      boolean("directApply", "Applications taken on this site"),
      text("identifier", "Reference"),
    ],
    summaryKey: "title",
    docsUrl: `${GOOGLE}/job-posting`,
    defaults: { hiringOrganization: { "@type": "Organization" }, jobLocation: { "@type": "Place", address: { "@type": "PostalAddress" } } },
  },
  {
    alias: "VideoObject",
    label: "Video",
    description: "A video embedded on this page.",
    icon: "icon-video",
    group: "Media",
    topLevel: true,
    fields: [
      text("name", "Title", { required: true }),
      textarea("description", "Description", { required: true }),
      list("thumbnailUrl", "Thumbnails", ofImage({ as: "url" }), { required: true }),
      datetime("uploadDate", "Upload date", { required: true }),
      duration("duration", "Duration", { recommended: true, description: "ISO 8601 duration, for example PT1M30S.", placeholder: "PT1M30S" }),
      url("contentUrl", "Video file URL", { recommended: true }),
      url("embedUrl", "Embed URL", { recommended: true }),
      entity("publisher", "Publisher", ["Organization"]),
      number("interactionCount", "View count"),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/video`,
  },
  {
    alias: "ImageObject",
    label: "Image",
    description: "A key image on the page, with credit and licence.",
    icon: "icon-picture",
    group: "Media",
    topLevel: true,
    fields: [
      image("contentUrl", "Image", { required: true, as: "url" }),
      text("name", "Title"),
      text("creditText", "Credit", { recommended: true }),
      url("license", "Licence URL", { recommended: true }),
      url("acquireLicensePage", "Where to licence it"),
      entity("creator", "Creator", ["Person", "Organization"]),
      text("copyrightNotice", "Copyright notice"),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/image-license-metadata`,
  },
  {
    alias: "ItemList",
    label: "Item list",
    description: "An ordered list of pages, such as a listing's contents.",
    icon: "icon-bulleted-list",
    group: "Other",
    topLevel: true,
    fields: [
      text("name", "Name"),
      list("itemListElement", "Items", ofEntity(["ListItem"]), { required: true, min: 1, autoPosition: true }),
    ],
    summaryKey: "name",
    docsUrl: `${GOOGLE}/carousel`,
  },
];

export const catalogue: readonly TypeDefinition[] = [...topLevel, ...nested];

const byAlias = new Map(catalogue.map((definition) => [definition.alias, definition]));

/** Variants share their family's definition: `BlogPosting` resolves to the Article definition. */
const byVariant = new Map<string, TypeDefinition>();
for (const definition of catalogue) {
  for (const variant of definition.typeVariants ?? []) {
    if (!byVariant.has(variant.value)) byVariant.set(variant.value, definition);
  }
}

export function getDefinition(alias: string): TypeDefinition | undefined {
  return byAlias.get(alias) ?? byVariant.get(alias);
}

export function topLevelDefinitions(): TypeDefinition[] {
  return catalogue.filter((definition) => definition.topLevel);
}

export const groupOrder: readonly string[] = ["Pages & content", "Organisation & people", "Products & services", "Events & jobs", "Media", "Other"];
